theme = "e-gelion"
confirm-before-quit = false

# -- FONTS -- 
[fonts]
size = 20
# family = "FiraCode Nerd Font"
# family = "JetBrains Mono"
# family = "Iosevka Nerd Font"
# family = "Terminess Nerd Font"
family = "MesloLGL Nerd Font"


# -- CURSOR -- 
[cursor]
shape = 'block'
blinking = true
blinking-interval = 500

# -- WINDOW -- 
[window]
decorations = "Disabled"
windows-corner-preference = "Round"

# -- SHELL --
[shell]
program = "wsl.exe"
args = ["~"]

# -- NAVIGATION --
[navigation]
mode = "Bookmark"




# -- BINDINGS --
[bindings]
keys = [
{key = "n", with = "control", action = "SelectNextSplit"}
]


